name: "Wakeup Azure DB"
description: "Wakeup a sleeping (auto-paused) Azure database"
inputs:
  server:
    description: "Database server name"
  port:
    description: "Database server port (default: 1433)"
  instance:
    description: "Instance name (optional)"
  database:
    description: "Database name (optional)"
  user:
    description: "SQL username"
  password:
    description: "SQL password"
  dsn:
    description: >
      Connection string.
      Incompatible with server, port, instance, database, user, and password inputs.
      Provide either a DSN or separate server, port, instance, database, user, and password values.

runs:
  using: docker
  image: docker://ghcr.io/redmer/azure-wakeup-db
  env:
    WAKEUP_SERVER: ${{ inputs.server }}
    WAKEUP_PORT: ${{ inputs.port }}
    WAKEUP_INSTANCE: ${{ inputs.instance }}
    WAKEUP_DATABASE: ${{ inputs.database }}
    WAKEUP_USER: ${{ inputs.user }}
    WAKEUP_PASSWORD: ${{ inputs.password }}
    WAKEUP_DSN: ${{ inputs.dsn }}

branding:
  icon: sunrise
  color: orange
