name: "Wakeup Azure DB"
description: "Wakeup a sleeping Azure database"
inputs:
  server:
    description: "Server name for the database"
  port:
    description: "Port for the database (default: 1433)"
  instance:
    description: "Instance name for the database (optional)"
  database:
    description: "Database name (optional)"
  user:
    description: "Username for the database"
  password:
    description: "Password for the database"
  dsn:
    description: >
      Database connection string of the database.
      Incompatible with server, port, instance, database, user, and password inputs.
      Provide either a DSN or separate server, port, instance, database, user, and password values.

runs:
  using: docker
  image: ghcr.io/redmer/azure-wakeup-db
  env:
    WAKEUP_SERVER: ${{ inputs.server }}
    WAKEUP_PORT: ${{ inputs.port }}
    WAKEUP_INSTANCE: ${{ inputs.instance }}
    WAKEUP_DATABASE: ${{ inputs.database }}
    WAKEUP_USER: ${{ inputs.user }}
    WAKEUP_PASSWORD: ${{ inputs.password }}
    WAKEUP_DSN: ${{ inputs.dsn }}

branding:
  icon: sunrise
  color: orange
